name: Build

on: [ push, pull_request ]

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod -R 777 *
      - run: ./gradlew clean --scan
      - run: ./gradlew assemble --scan
      - run: ./gradlew check --scan
